version: "3"

services:
    server:
        platform: linux/x86_64
        build:
            dockerfile: Dockerfile
            args:
                - DEBUG=1
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE
        ports:
            - "8000:8000"
        volumes:
            - "./:/app"
        environment:
            - REDIS_URL=redis://redis-db:6379

    redis-db:
        image: redis:alpine
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli","ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    debug-container:
        profiles:
            - debug
        build:
            context: .
            args:
                - DEBUG=1
        volumes:
            - "./:/app"
        command: gdb -v