name: "deploy"

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Login to GH Container Rergistry
          env:
            CR_PAT: ${{ secrets.GCR_TOKEN }}
          run: docker login ghcr.io -u UKnowWhoIm --password $CR_PAT

        - name: Build, tag, and push the image to GH CR
          id: build-image
          env:
            IMAGE_NAME: ghcr.io/uknowwhoim/chess
            IMAGE_TAG: latest
          run: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            echo "Pushing image to GCR..."
            docker push $IMAGE_NAME:$IMAGE_TAG
            echo "::set-output name=image::$IMAGE_NAME:$IMAGE_TAG"

        - name: Deploy To EC2
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.AWS_EC2_HOST }}
            username: ${{ secrets.AWS_EC2_USER }}
            key: ${{ secrets.AWS_EC2_KEY }}
            port: ${{ secrets.AWS_EC2_PORT }}
            script: |
              echo $GCR_PAT | docker login ghcr.io -u UKnowWhoIm --password-stdin
              docker pull ghcr.io/uknowwhoim/chess:latest
              ./launch_container ghcr.io/uknowwhoim/chess:latest chess.env chess-bot
